<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>Exe</OutputType>
	<NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup Label="Usings">
	<Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Immediate.Handlers" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	<PackageReference Include="Microsoft.Extensions.Localization" />
	<PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
	<PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
	<EmbeddedResource Update="Resources\Validators.resx">
	  <Generator>ResXFileCodeGenerator</Generator>
	  <LastGenOutput>Validators.Designer.cs</LastGenOutput>
	</EmbeddedResource>
	<EmbeddedResource Update="Resources\Validators.fr-CA.resx">
	  <Generator>ResXFileCodeGenerator</Generator>
	  <LastGenOutput>Validators.fr-CA.Designer.cs</LastGenOutput>
	</EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
	<Compile Update="Resources\Validators.Designer.cs">
	  <DesignTime>True</DesignTime>
	  <AutoGen>True</AutoGen>
	  <DependentUpon>Validators.resx</DependentUpon>
	</Compile>
	<Compile Update="Resources\Validators.fr-CA.Designer.cs">
	  <DesignTime>True</DesignTime>
	  <AutoGen>True</AutoGen>
	  <DependentUpon>Validators.fr-CA.resx</DependentUpon>
	</Compile>
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="../../src/Immediate.Validations.Shared/Immediate.Validations.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net8.0' ">roslyn4.8</RoslynVersion>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net10.0' ">roslyn5.0</RoslynVersion>
	<RoslynVersion Condition=" '$(TargetFramework)' == 'net11.0' ">roslyn5.9</RoslynVersion>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="../../src/Immediate.Validations.Analyzers/Immediate.Validations.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=$(RoslynVersion)</SetTargetFramework>
	</ProjectReference>

	<ProjectReference Include="../../src/Immediate.Validations.CodeFixes/Immediate.Validations.CodeFixes.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=$(RoslynVersion)</SetTargetFramework>
	</ProjectReference>

	<ProjectReference Include="../../src/Immediate.Validations.Generators/Immediate.Validations.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false">
	  <SetTargetFramework>TargetFramework=$(RoslynVersion)</SetTargetFramework>
	</ProjectReference>
  </ItemGroup>

</Project>
